spring:
  shardingsphere:
    datasource:
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/trans_sa_pdb_0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        # Druid配置
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/trans_sa_pdb_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        # Druid配置
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/trans_sa_pdb_2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        # Druid配置
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      ds3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/trans_sa_pdb_3?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        # Druid配置
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
      config:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/trans_sa_npdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        # Druid配置
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
    rules:
      sharding:
        tables:
          sfm_sa_client_no:
            actual-data-nodes: config.sfm_sa_client_no
          sfm_sa_ta_client:
            actual-data-nodes: config.sfm_sa_ta_client
          sfm_sa_acc_req_table:
            actual-data-nodes: ds${0..3}.sfm_sa_acc_req_table_${0..7}
            table-strategy:
              standard:
                sharding-column: partition_key
                sharding-algorithm-name: acc-req-table-inline
            database-strategy:
              standard:
                sharding-column: partition_key
                sharding-algorithm-name: acc-req-db-inline
          sfm_sa_client_info_table:
            actual-data-nodes: ds${0..3}.sfm_sa_client_info_table_${0..7}
            table-strategy:
              standard:
                sharding-column: partition_key
                sharding-algorithm-name: client-info-table-inline
            database-strategy:
              standard:
                sharding-column: partition_key
                sharding-algorithm-name: client-info-db-inline
        sharding-algorithms:
          acc-req-table-inline:
            type: INLINE
            props:
              algorithm-expression: sfm_sa_acc_req_table_$->{partition_key % 8}
          acc-req-db-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{partition_key % 8 % 4}
          client-info-table-inline:
            type: INLINE
            props:
              algorithm-expression: sfm_sa_client_info_table_$->{partition_key % 8}
          client-info-db-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{partition_key % 8 % 4}
    props:
      sql-show: true