spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trans-sfm-client?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  batch:
    job:
      enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 确保下划线到驼峰命名的转换开启
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      # 表名和字段名使用下划线命名
      table-underline: true
      column-underline: true
      # 明确指定数据库类型为MySQL
      db-type: mysql
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.trans.sfm.client.batch: DEBUG
    org.springframework.batch: DEBUG
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: ./logs/trans-sfm-client-batch.log
    max-size: 100MB
    max-history: 30