server:
  port: 8080

spring:
  application:
    name: trans-sfm-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务器地址
    gateway:
      routes:
        - id: trans-sfm-sa-online
          uri: lb://trans-sfm-sa-online
          predicates:
            - Path=/sa/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# Feign配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"