server:
  port: 8080

spring:
  application:
    name: trans-sfm-client-online

# 日志配置
logging:
  level:
    com.trans.sfm.client.online: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# Feign配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

# 网关地址配置
gateway:
  url: http://localhost:9000