CREATE TABLE `sfm_sa_acc_req_table_0` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `partition_key` bigint(20) unsigned NOT NULL COMMENT '分片键',
  `trans_id` varchar(64) NOT NULL DEFAULT '' COMMENT '全局流水号',
  `sub_trans_seq` varchar(32) NOT NULL DEFAULT '' COMMENT '子流水号',
  `trans_date` varchar(8) NOT NULL DEFAULT '' COMMENT '交易日期',
  `trans_time` int(11) DEFAULT '0' COMMENT '交易时间',
  `partner_serial_no` varchar(32) NOT NULL DEFAULT '' COMMENT '合作方流水',
  `partner_code` varchar(32) NOT NULL DEFAULT '' COMMENT '合作方代码',
  `partner_channel` varchar(32) NOT NULL DEFAULT '' COMMENT '合作方渠道',
  `biz_type` varchar(32) NOT NULL DEFAULT '' COMMENT '业务类别',
  `ta_client` varchar(32) NOT NULL DEFAULT '' COMMENT '基交交易账号',
  `ta_code` varchar(32) NOT NULL DEFAULT '' COMMENT 'TA代码',
  `asset_acc` varchar(20) NOT NULL DEFAULT '' COMMENT '理财账号',
  `client_type` varchar(1) NOT NULL DEFAULT '' COMMENT '客户类型: 0-机构,1-个人',
  `client_no` bigint(20)  DEFAULT NULL COMMENT '客户号',
  `bank_acc` varchar(128) DEFAULT '' COMMENT '银行账号',
  `trans_account_type` varchar(1) DEFAULT '' COMMENT '交易介质类型0-卡号,1-账号',
  `trans_account` varchar(128) DEFAULT '' COMMENT '交易介质',
  `id_type` varchar(8) DEFAULT '' COMMENT '证件类型',
  `id_code` varchar(128) DEFAULT '' COMMENT '证件号码',
  `client_name` varchar(18) DEFAULT '' COMMENT '客户名称',
  `client_short_name` varchar(18) DEFAULT '' COMMENT '客户简称',
  `sex` varchar(1) DEFAULT '' COMMENT '性别',
  `birthday` int(11) DEFAULT '0' COMMENT '出生日期',
  `address` varchar(512) DEFAULT '' COMMENT '通讯地址',
  `post_code` varchar(6) DEFAULT '' COMMENT '邮政编码',
  `mobile` varchar(20) DEFAULT '' COMMENT '手机号码',
  `tel` varchar(20) DEFAULT '' COMMENT '联系电话',
  `fax` varchar(20) DEFAULT '' COMMENT '传真号码',
  `email` varchar(40) DEFAULT '' COMMENT '电子邮箱',
  `send_mode` varchar(8) DEFAULT '' COMMENT '对账单发送方式',
  `send_freq` varchar(1) DEFAULT '' COMMENT '对账单寄送频率',
  `div_mode` varchar(1) DEFAULT '' COMMENT '分红方式',
  `asso_date` int(11) DEFAULT '0' COMMENT '关联日期',
  `frozen_cause` varchar(1) DEFAULT '' COMMENT '冻结原因:0-司法 1-质押',
  `asso_serial_no` varchar(32) DEFAULT '' COMMENT 'TA的确认流水号',
  `input_type` varchar(2) DEFAULT '' COMMENT '机构投资人类型',
  `repr_name` varchar(128) DEFAULT '' COMMENT '法人代表姓名',
  `repr_id_type` varchar(8) DEFAULT '' COMMENT '法人代表证件类型',
  `repr_id_code` varchar(128) DEFAULT '' COMMENT '法人代表证件号码',
  `actor_name` varchar(128) DEFAULT '' COMMENT '经办人姓名',
  `actor_id_type` varchar(8) DEFAULT '' COMMENT '经办人证件类型',
  `actor_id_code` varchar(128) DEFAULT '' COMMENT '经办人证件号码',
  `client_manager` varchar(32) DEFAULT '' COMMENT '客户经理',
  `remark` varchar(255) DEFAULT '' COMMENT '备注:银行调增调减原因/强行赎回等原因',
  `nationality` varchar(3) NOT NULL DEFAULT '' COMMENT '国籍',
  `occupation` varchar(8) NOT NULL DEFAULT '' COMMENT '职业代码',
  `validity` int(11) NOT NULL DEFAULT '0' COMMENT '证件有效截止日期',
  `industry` varchar(4) DEFAULT '' COMMENT '行业',
  `region_code` varchar(8) DEFAULT '' COMMENT '交易所在地区编号',
  `education` varchar(4) DEFAULT '' COMMENT '学历',
  `income` decimal(18,2) DEFAULT '0.00' COMMENT '年收入',
  `branch_code` varchar(20) DEFAULT '' COMMENT '网点号码',
  `trade_method` varchar(20) DEFAULT '' COMMENT '交易手段',
  `minor_flag` varchar(1) DEFAULT '' COMMENT '未成年标志 0-否,1-是',
  `transactor_id_type` varchar(1) DEFAULT '' COMMENT '经办人识别方式 1-书面委托,2-印鉴,3-密码,4-证件',
  `net_no` varchar(9) DEFAULT '' COMMENT '操作网点编号',
  `risk_level` varchar(6) DEFAULT '' COMMENT '风险等级',
  `risk_date` int(11) DEFAULT '0' COMMENT '风险有效截止日期',
  `inst_actor_id_code_date` int(11) DEFAULT '0' COMMENT '机构经办人身份证有效日期',
  `inst_repr_id_code_date` int(11) DEFAULT '0' COMMENT '机构法人身份证有效日期',
  `inst_repr_manage_range` varchar(512) DEFAULT '' COMMENT '机构法人经营范围',
  `control_holder` varchar(128) DEFAULT '' COMMENT '控股股东',
  `actual_controller` varchar(128) DEFAULT '' COMMENT '实际控制人',
  `marriage_status` varchar(1) DEFAULT '' COMMENT '婚姻状态',
  `family_num` int(2) DEFAULT NULL COMMENT '家庭人口数',
  `penates` decimal(20,2) DEFAULT '0.00' COMMENT '家庭资产',
  `media_hobby` varchar(1) DEFAULT '' COMMENT '媒体偏好',
  `english_first_name` varchar(32) DEFAULT '' COMMENT '投资人英文名',
  `english_family_name` varchar(32) DEFAULT '' COMMENT '投资人英文姓',
  `corpo_property` varchar(2) DEFAULT '' COMMENT '企业质',
  `staff_num` int(8) DEFAULT NULL COMMENT '员工人数',
  `hobby_type` varchar(8) DEFAULT '' COMMENT '兴趣爱好',
  `curr_nation` varchar(3) DEFAULT '' COMMENT '现居国家',
  `curr_province` varchar(8) DEFAULT '' COMMENT '现居地址-省',
  `curr_city` varchar(8) DEFAULT '' COMMENT '现居地址-市',
  `curr_county` varchar(8) DEFAULT '' COMMENT '现居地址-县',
  `deal_mode` varchar(1) DEFAULT '' COMMENT '受理方式',
  `trans_status` varchar(3) NOT NULL DEFAULT '' COMMENT '交易状态',
  `ret_code` varchar(16) DEFAULT NULL COMMENT '返回码',
  `ret_msg` varchar(256) DEFAULT NULL COMMENT '返回信息',
  `sys_code` varchar(8) NOT NULL DEFAULT '' COMMENT '所属系统',
  `req_ext_data` varchar(2048) DEFAULT NULL COMMENT '请求扩展数据',
  `ret_ext_data` varchar(2048) DEFAULT NULL COMMENT '返回扩展数据',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_trans_seq` (`trans_id`,`sub_trans_seq`) USING BTREE,
  UNIQUE KEY `uniq_serial_no` (`partner_serial_no`,`partner_code`) USING BTREE,
  KEY `idx_client_no` (`client_no`) USING BTREE
) ENGINE=InnoDB COMMENT='账户申请流水表--水平';

CREATE TABLE `sfm_sa_client_info_table_0` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `partition_key` bigint(20) unsigned NOT NULL COMMENT '分片键',
  `partner_code` varchar(32) NOT NULL DEFAULT '' COMMENT '合作方代码',
  `partner_channel` varchar(32) NOT NULL DEFAULT '' COMMENT '合作方渠道',
  `customer_id` VARCHAR ( 64 ) NOT NULL COMMENT '客户系统内部ID',
  `client_type` varchar(1) NOT NULL DEFAULT '' COMMENT '客户类型: 0-机构,1-个人',
  `client_no` bigint(20)  DEFAULT NULL COMMENT '客户号',
  `client_group` varchar(1) NOT NULL DEFAULT '' COMMENT '客户分组',
  `id_type` varchar(8) DEFAULT '' COMMENT '证件类型',
  `id_code` varchar(128) DEFAULT '' COMMENT '证件号码',
  `client_name` varchar(18) DEFAULT '' COMMENT '客户名称',
  `client_short_name` varchar(18) DEFAULT '' COMMENT '客户简称',
  `address` varchar(512) DEFAULT '' COMMENT '通讯地址',
  `post_code` varchar(6) DEFAULT '' COMMENT '邮政编码',
  `mobile` varchar(20) DEFAULT '' COMMENT '手机号码',
  `tel` varchar(20) DEFAULT '' COMMENT '联系电话',
  `fax` varchar(20) DEFAULT '' COMMENT '传真号码',
  `email` varchar(40) DEFAULT '' COMMENT '电子邮箱',
  `sex` varchar(1) DEFAULT '' COMMENT '性别',
  `send_mode` varchar(8) DEFAULT '' COMMENT '对账单发送方式',
  `send_freq` varchar(1) DEFAULT '' COMMENT '对账单寄送频率',
  `risk_level` varchar(6) DEFAULT '' COMMENT '风险等级',
  `risk_date` int(11) DEFAULT '0' COMMENT '风险有效截止日期',
  `birthday` int(11) DEFAULT '0' COMMENT '出生日期',
  `validity` int(11) NOT NULL DEFAULT '0' COMMENT '证件有效截止日期',
  `occupation` varchar(8) NOT NULL DEFAULT '' COMMENT '职业代码',
  `education` varchar(4) DEFAULT '' COMMENT '学历',
  `income` decimal(18,2) DEFAULT '0.00' COMMENT '年收入',
  `nationality` varchar(3) NOT NULL DEFAULT '' COMMENT '国籍',
  `prd_types` varchar(128) NOT NULL DEFAULT '' COMMENT '开通业务',
  `client_manager` varchar(32) DEFAULT '' COMMENT '客户经理',
  `curr_nation` varchar(3) DEFAULT '' COMMENT '现居国家',
  `curr_province` varchar(8) DEFAULT '' COMMENT '现居地址-省',
  `curr_city` varchar(8) DEFAULT '' COMMENT '现居地址-市',
  `curr_county` varchar(8) DEFAULT '' COMMENT '现居地址-县',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_client_no` (`client_no`) USING BTREE
) ENGINE=InnoDB COMMENT='客户信息表--水平';

