server:
  port: 8081

spring:
  application:
    name: trans-sfm-sa-online
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trans-sfm-client?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务器地址
  # MCP Server 配置
  ai:
    mcp:
      server:
        endpoint: /mcp
        enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      table-underline: true

# Druid监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"